services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./certs:/app/certs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - HOST_IP=192.168.0.131  # Ваш реальный IP адрес
